### ISSUE TITLE
Single crate workspace doesn't work.

### ISSUE THREAD

**Issue by zie1ony** [odradev/cargo-odra#80]
I wanted to have repository with two crates:
- `contracts` - crate that produces `wasm` files,
- `client` - some code to interact with contracts.

Unfortunetely with just one create `contracts` in the workspace I was not able to test it against Casper's VM, because of the missing `*.wasm` file in crates's `wasm` directory. It is only copied into root's `wasm` directory.

#### Bonus error
If you name your crate's directory `aaa-contracts` it will try to copy wasm file into `aaa_contracts/wasm` (note underscore).

**Comment by kubaplas** [comment]
Fixed by #83
